### ISSUE TITLE
The game crash bug still exists

### ISSUE THREAD

**Issue by hexadecimal233** [b0iizz/minecraft-advancednbttooltip#43]
#42 #41 #40 can still be triggered in the latest build, conflicting with the same old mods
``java.lang.IllegalArgumentException: Unknown TooltipComponent
	at net.minecraft.class_5684.method_32663(class_5684.java:22)
	at me.b0iizz.advancednbttooltip.gui.CustomTooltipRenderer.fromTooltipData(CustomTooltipRenderer.java:63)
	at java.base/java.util.Optional.map(Optional.java:260)
	at me.b0iizz.advancednbttooltip.gui.CustomTooltipRenderer.renderTooltip(CustomTooltipRenderer.java:55)
	at me.b0iizz.advancednbttooltip.gui.CustomTooltipRenderer.renderTooltip(CustomTooltipRenderer.java:47)
	at net.minecraft.class_437.handler$zzc000$renderTooltipHook(class_437.java:737)
	at net.minecraft.class_437.method_25409(class_437.java)
	at net.minecraft.class_481.method_25409(class_481.java:731)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_481.method_25394(class_481.java:692)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
``

**Comment by b0iizz** [comment]
It worked fine for me when i tested it... Mhmmm

**Comment by hexadecimal233** [comment]
inspecio mod will crash it and other map & flag preview mod will crash the game

**Comment by b0iizz** [comment]
But inspecio is for Quilt?

**Comment by hexadecimal233** [comment]
I mean the mods like inspecio

**Comment by hexadecimal233** [comment]
that renders maps flags and other things

**Comment by b0iizz** [comment]
can you link some of these mods so i can test them and see what i can do to fix the incompatibility?

**Comment by ThebestkillerTBK** [comment]
[inspecio 1.18 for fabric
](https://www.curseforge.com/minecraft/mc-mods/inspecio/download/3671909)

**Comment by hexadecimal233** [comment]
[link](https://meteorclient.com/)

**Comment by b0iizz** [comment]
Why does every mod have their own TooltipComponent Hook :( .... I will see what i can do

**Comment by hexadecimal233** [comment]
@b0iizz any updates?

**Comment by b0iizz** [comment]
School started so I don't have as much time so I'm busy with other stuff but I will try to think of a solution

**Comment by hexadecimal233** [comment]
i still cannot find a solution 🤔

**Comment by hexadecimal233** [comment]
@b0iizz and why you hook render but not getTooltip

**Comment by b0iizz** [comment]
Because getTooltip does not work with TooltipComponents

**Comment by hexadecimal233** [comment]
> Because getTooltip does not work with TooltipComponents

You can just append your tooltip
